from sqlalchemy import Column, String, Integer, DECIMAL
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()


class Zotfov(Base):
    __tablename__ = 'zotfvo1'

    id = Column(Integer, primary_key=True)
    cocd = Column(Integer, nullable=True)
    tx = Column(String(255), nullable=True)
    pos_receipt = Column(String(255), nullable=True)
    item = Column(String(255), nullable=True)
    year = Column(String(255), nullable=True)
    period = Column(String(255), nullable=True)
    posting_date = Column(String(255), nullable=True)
    document_created = Column(String(255), nullable=True)
    paymt_date = Column(String(255), nullable=True)
    billt = Column(String(255), nullable=True)
    invoice_id = Column(String(255), nullable=True)
    invoice_no = Column(String(255), nullable=True)
    invoice_date = Column(String(255), nullable=True)
    tax_base_amt_in_lc = Column(DECIMAL(19, 2), nullable=True)
    tax_amt_in_lc = Column(DECIMAL(19, 2), nullable=True)
    crcy = Column(String(255), nullable=True)
    tax_base_amt_in_gc = Column(DECIMAL(19, 2), nullable=True)
    tax_amt_in_gc = Column(DECIMAL(19, 2), nullable=True)
    lcur2 = Column(String(255), nullable=True)
    store = Column(String(255), nullable=True)
    store_name = Column(String(255), nullable=True)
    postal_code = Column(String(255), nullable=True)
    store_address = Column(String(255), nullable=True)
    trs_key = Column(String(255), nullable=True)
    checking_in_lc = Column(DECIMAL(19, 2), nullable=True)
    checking_in_gc = Column(DECIMAL(19, 2), nullable=True)
    tax_Gross_amt_in_doc_curr = Column(DECIMAL(19, 2), nullable=True)
    created_on = Column(String(255), nullable=True)
    amount = Column(DECIMAL(19, 2), nullable=True)
    article_no = Column(String(255), nullable=True)
    material_description = Column(String(255), nullable=True)
    billed_qty = Column(String(255), nullable=True)
    gl_acct = Column(String(255), nullable=True)
    posting_status = Column(String(255), nullable=True)
    mdse_catgry_desc = Column(String(255), nullable=True)
    prod_class = Column(String(255), nullable=True)
    prod_class_desc = Column(String(255), nullable=True)
    fiscal_code = Column(String(255), nullable=True)
    customer_ho_branch_no = Column(String(255), nullable=True)